# Tensor Basics

In [16]:
import torch

# Creating a simple 1D tensor
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print("1D Tensor:", tensor_1d)

# Creating a 2D tensor (matrix)
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("\n2D Tensor:")
print(tensor_2d)

# Tensor properties
print("\nShape of 2D tensor:", tensor_2d.shape)
print("Data type:", tensor_2d.dtype)

# Creating a tensor of zeros and ones
zeros = torch.zeros((3, 3))
ones = torch.ones((2, 4))
print("\nTensor of zeros:")
print(zeros)
print("\nTensor of ones:")
print(ones)


1D Tensor: tensor([1, 2, 3, 4, 5])

2D Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Shape of 2D tensor: torch.Size([2, 3])
Data type: torch.int64

Tensor of zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Tensor of ones:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [2]:
# Basic operations
sum_tensors = tensor_1d + torch.tensor([5, 4, 3, 2, 1])
print("\nSum of tensors:", sum_tensors)


Sum of tensors: tensor([6, 6, 6, 6, 6])


In [3]:
# Element-wise multiplication
product = tensor_2d * 2
print("\nElement-wise multiplication:")
print(product)



Element-wise multiplication:
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [4]:
# Matrix multiplication
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])
matrix_product = torch.matmul(matrix_a, matrix_b)
print("\nMatrix multiplication result:")
print(matrix_product)


Matrix multiplication result:
tensor([[19, 22],
        [43, 50]])


In [5]:
# Reshaping tensors
reshaped = tensor_2d.view(3, 2)
print("\nReshaped tensor:")
print(reshaped)


Reshaped tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [6]:
# Transposing tensors
transposed = tensor_2d.t()
print("\nTransposed tensor:")
print(transposed)


Transposed tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [7]:
print('tensor_2d',tensor_2d)

# Slicing tensors
sliced = tensor_2d[:, 1]
print("\nSecond column of 2D tensor:")
print(sliced)


print(':0',tensor_2d[:, 0])
print(':1',tensor_2d[:, 1])
print(':2',tensor_2d[:, 2])


print(':0',tensor_2d[0, :])
print(':1',tensor_2d[1, :])
# similar to what we do with numpy arrays

tensor_2d tensor([[1, 2, 3],
        [4, 5, 6]])

Second column of 2D tensor:
tensor([2, 5])
:0 tensor([1, 4])
:1 tensor([2, 5])
:2 tensor([3, 6])
:0 tensor([1, 2, 3])
:1 tensor([4, 5, 6])


In [8]:
# Stacking tensors
stacked = torch.stack((tensor_1d, tensor_1d))
print("\nStacked tensors:")
print(stacked)


Stacked tensors:
tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])


In [9]:
# Converting tensors to numpy
numpy_array = tensor_1d.numpy()
print("\nConverted to numpy array:")
print(numpy_array)



Converted to numpy array:
[1 2 3 4 5]


In [10]:
# Moving tensors to GPU (if available)
if torch.cuda.is_available():
    tensor_gpu = tensor_1d.to('cuda')
    print("\nTensor moved to GPU")
else:
    print('NO GPU')

NO GPU


In [11]:
import numpy as np
import torch
import time

# To show why tensor works better, we are creating a large list, NumPy array, and PyTorch tensor
size = 1000000
python_list = [i for i in range(size)]
numpy_array = np.array(python_list)
torch_tensor = torch.tensor(python_list)

# i am trying to show you a element-wise multiplication performance comparison
# Python list
start = time.time()
python_result = [x * 2 for x in python_list]
end = time.time()
print(f"Python list time: {end - start:.5f} seconds")

# NumPy array
start = time.time()
numpy_result = numpy_array * 2
end = time.time()
print(f"NumPy array time: {end - start:.5f} seconds")

# PyTorch tensor
start = time.time()
torch_result = torch_tensor * 2
end = time.time()
print(f"PyTorch tensor time: {end - start:.5f} seconds")

# Broadcasting example
numpy_matrix = np.ones((3, 3))
torch_matrix = torch.ones((3, 3))

print("\nNumPy broadcasting:")
print(numpy_matrix + np.array([1, 2, 3]))

print("\nPyTorch broadcasting:")
print(torch_matrix + torch.tensor([1, 2, 3]))

# try this out 
# Python list time: 0.45487 seconds
# NumPy array time: 0.02181 seconds
# PyTorch tensor time: 0.08847 seconds

Python list time: 0.11439 seconds
NumPy array time: 0.00707 seconds
PyTorch tensor time: 0.00805 seconds

NumPy broadcasting:
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]

PyTorch broadcasting:
tensor([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]])


In [12]:
# GPU acceleration with PyTorch (if available) # this would show you how fast a tensor is better
if torch.cuda.is_available():
    device = torch.device('cuda')
    torch_tensor_gpu = torch.tensor(python_list, device=device)
    start = time.time()
    torch_result_gpu = torch_tensor_gpu * 2
    end = time.time()
    print(f"PyTorch tensor on GPU time: {end - start:.5f} seconds")
else:
    print("GPU not available")


GPU not available


# Some sample cases where we will use these Tensor.
### just showing some examples, we will learn about how to write these in details in upcoming classes  

In [13]:
import torch
import torch.nn.functional as F

# Simulating a simple artificial neuron

def simple_neuron(inputs, weights, bias):
    # Convert inputs and weights to tensors
    inputs = torch.tensor(inputs, dtype=torch.float32)
    weights = torch.tensor(weights, dtype=torch.float32)
    bias = torch.tensor(bias, dtype=torch.float32)

    # Weighted sum of inputs and weights + bias
    z = torch.dot(inputs, weights) + bias

    # Applying activation function (Sigmoid)
    output = torch.sigmoid(z)

    return output

# Example inputs, weights, and bias
inputs = [0.5, 0.8, 0.3]
weights = [0.4, 0.7, 0.2]
bias = 0.1

# Get the neuron's output
output = simple_neuron(inputs, weights, bias)
print(f"Neuron Output: {output.item():.4f}")

Neuron Output: 0.7150


In [14]:
import torch
import torch.nn as nn
import torch.optim as optim

# Representing data with tensors
# Simulating a dataset: 100 samples, 3 features
X = torch.rand((100, 3))  # Inputs
y = torch.randint(0, 2, (100,))  # Binary labels

# Building a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(3, 5)
        self.fc2 = nn.Linear(5, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        return x

# Initializing model, loss, and optimizer
model = SimpleNN()
criterion = nn.BCELoss()  # Binary Cross-Entropy Loss
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
epochs = 5
for epoch in range(epochs):
    # Forward pass
    outputs = model(X).squeeze()
    loss = criterion(outputs, y.float())

    # Backward pass
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

# Batch processing
batch_size = 10
for i in range(0, len(X), batch_size):
    X_batch = X[i:i+batch_size]
    y_batch = y[i:i+batch_size]
    batch_output = model(X_batch)
    print(f"Batch {i//batch_size + 1} Output: {batch_output.squeeze().detach()}")


Epoch [1/5], Loss: 0.7217
Epoch [2/5], Loss: 0.7215
Epoch [3/5], Loss: 0.7213
Epoch [4/5], Loss: 0.7211
Epoch [5/5], Loss: 0.7209
Batch 1 Output: tensor([0.5998, 0.5911, 0.5915, 0.5894, 0.5976, 0.5899, 0.6039, 0.5916, 0.5901,
        0.6165])
Batch 2 Output: tensor([0.5911, 0.5909, 0.5857, 0.5956, 0.5971, 0.5998, 0.6079, 0.5882, 0.5811,
        0.6156])
Batch 3 Output: tensor([0.5998, 0.5812, 0.5869, 0.5835, 0.6166, 0.6019, 0.6082, 0.5984, 0.5866,
        0.5883])
Batch 4 Output: tensor([0.6008, 0.5880, 0.5937, 0.6002, 0.6066, 0.5912, 0.5962, 0.5931, 0.6000,
        0.5865])
Batch 5 Output: tensor([0.5948, 0.5915, 0.6009, 0.6100, 0.6010, 0.6128, 0.6113, 0.5973, 0.5993,
        0.5922])
Batch 6 Output: tensor([0.6010, 0.5895, 0.5985, 0.5909, 0.5939, 0.5969, 0.5878, 0.6153, 0.5970,
        0.6173])
Batch 7 Output: tensor([0.5907, 0.5930, 0.5840, 0.5892, 0.5979, 0.5856, 0.5858, 0.5946, 0.5936,
        0.6013])
Batch 8 Output: tensor([0.5821, 0.5879, 0.5974, 0.6166, 0.6039, 0.5980, 0.5953,

In [15]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 1. Loading the California Housing dataset
california = fetch_california_housing()
X, y = california.data, california.target

# Standardizing the data
scaler = StandardScaler()
X = scaler.fit_transform(X)
y = y.reshape(-1, 1)

# Splitting the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Converting to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

# 2. Building a simple regression model
class RegressionNN(nn.Module):
    def __init__(self):
        super(RegressionNN, self).__init__()
        self.fc1 = nn.Linear(X_train.shape[1], 10)
        self.fc2 = nn.Linear(10, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# 3. Initializing model, loss, and optimizer
model = RegressionNN()
criterion = nn.MSELoss()  # Mean Squared Error Loss for regression
optimizer = optim.SGD(model.parameters(), lr=0.01)

# 4. Training loop
epochs = 20
for epoch in range(epochs):
    model.train()
    outputs = model(X_train)
    loss = criterion(outputs, y_train)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

# 5. Evaluation
model.eval()
y_pred = model(X_test).detach()
mse = criterion(y_pred, y_test)
print(f"Test MSE: {mse.item():.4f}")


Epoch [1/20], Loss: 5.4612
Epoch [2/20], Loss: 5.1539
Epoch [3/20], Loss: 4.8703
Epoch [4/20], Loss: 4.6076
Epoch [5/20], Loss: 4.3636
Epoch [6/20], Loss: 4.1366
Epoch [7/20], Loss: 3.9250
Epoch [8/20], Loss: 3.7274
Epoch [9/20], Loss: 3.5426
Epoch [10/20], Loss: 3.3695
Epoch [11/20], Loss: 3.2074
Epoch [12/20], Loss: 3.0554
Epoch [13/20], Loss: 2.9129
Epoch [14/20], Loss: 2.7793
Epoch [15/20], Loss: 2.6539
Epoch [16/20], Loss: 2.5362
Epoch [17/20], Loss: 2.4258
Epoch [18/20], Loss: 2.3222
Epoch [19/20], Loss: 2.2251
Epoch [20/20], Loss: 2.1341
Test MSE: 1.9885
